name: Hybrid App Build Process

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        sudo su 
        docker pull minddocdev/node-alpine:latest
        docker tag minddocdev/node-alpine:latest lalitku/hybrid-launch-artifact:${{ github.run_number }}
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lalitku
        password: Lalit/2698
    - name: Push
      run: |
          docker push lalitku/hybrid-launch-artifact:${{ github.run_number }}
    
  ucd:
    needs: [build]
    runs-on: self-hosted

    steps:
    - name: Import Component Into UCD
      run: |
        curl --insecure --request PUT 'https://10.115.211.229/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic a64c766f-9470-4f7d-b9fb-016157902241' --data '{"component": "Hybrid Versions","properties": {"version": ${{ github.run_number }},"description": ""}}'
    - name: Wait for 30s
      run: sleep 60
    - name: Create Snapshot
      run: |
        curl --insecure --request PUT 'https://10.115.211.229/cli/snapshot/createSnapshot' --header 'Content-Type: application/json' --header 'Authorization: Basic a64c766f-9470-4f7d-b9fb-016157902241' --data '{"name": ${{ github.run_number }},"application": "Only_For_Hybrid_Applications","description": "Some snapshot","versions": [{"Hybrid Versions": "latest"}]}'
